{
  "response": {
    "version": "0.1",
    "termsofService": "http:\/\/www.wunderground.com\/weather\/api\/d\/terms.html",
    "features": {
      "conditions": 1
    }
  },
  "current_observation": {
    "image": {
      "url": "http:\/\/icons.wxug.com\/graphics\/wu2\/logo_130x80.png",
      "title": "Weather Underground",
      "link": "http:\/\/www.wunderground.com"
    },
    "display_location": {
      "full": "Birmingham, AL",
      "city": "Birmingham",
      "state": "AL",
      "state_name": "Alabama",
      "country": "US",
      "country_iso3166": "US",
      "zip": "35201",
      "magic": "1",
      "wmo": "99999",
      "latitude": "33.52000046",
      "longitude": "-86.80000305",
      "elevation": "173.1"
    },
    "observation_location": {
      "full": "UAB HHB, Birmingham, Alabama",
      "city": "UAB HHB, Birmingham",
      "state": "Alabama",
      "country": "US",
      "country_iso3166": "US",
      "latitude": "33.500576",
      "longitude": "-86.806931",
      "elevation": "617 ft"
    },
    "estimated": {

    },
    "station_id": "KALBIRMI50",
    "observation_time": "Last Updated on July 21, 4:40 PM CDT",
    "observation_time_rfc822": "Fri, 21 Jul 2017 16:40:19 -0500",
    "observation_epoch": "1500673219",
    "local_time_rfc822": "Fri, 21 Jul 2017 16:41:13 -0500",
    "local_epoch": "1500673273",
    "local_tz_short": "CDT",
    "local_tz_long": "America\/Chicago",
    "local_tz_offset": "-0500",
    "weather": "Partly Cloudy",
    "temperature_string": "94.6 F (34.8 C)",
    "temp_f": 94.6,
    "temp_c": 34.8,
    "relative_humidity": "50%",
    "wind_string": "From the SE at 4.0 MPH Gusting to 14.0 MPH",
    "wind_dir": "SE",
    "wind_degrees": 128,
    "wind_mph": 4,
    "wind_gust_mph": "14.0",
    "wind_kph": 6.4,
    "wind_gust_kph": "22.5",
    "pressure_mb": "1015",
    "pressure_in": "29.97",
    "pressure_trend": "-",
    "dewpoint_string": "73 F (23 C)",
    "dewpoint_f": 73,
    "dewpoint_c": 23,
    "heat_index_string": "104 F (40 C)",
    "heat_index_f": 104,
    "heat_index_c": 40,
    "windchill_string": "NA",
    "windchill_f": "NA",
    "windchill_c": "NA",
    "feelslike_string": "104 F (40 C)",
    "feelslike_f": "104",
    "feelslike_c": "40",
    "visibility_mi": "10.0",
    "visibility_km": "16.1",
    "solarradiation": "--",
    "UV": "6",
    "precip_1hr_string": "0.00 in ( 0 mm)",
    "precip_1hr_in": "0.00",
    "precip_1hr_metric": " 0",
    "precip_today_string": "0.00 in (0 mm)",
    "precip_today_in": "0.00",
    "precip_today_metric": "0",
    "icon": "partlycloudy",
    "icon_url": "http:\/\/icons.wxug.com\/i\/c\/k\/partlycloudy.gif",
    "forecast_url": "http:\/\/www.wunderground.com\/US\/AL\/Birmingham.html",
    "history_url": "http:\/\/www.wunderground.com\/weatherstation\/WXDailyHistory.asp?ID=KALBIRMI50",
    "ob_url": "http:\/\/www.wunderground.com\/cgi-bin\/findweather\/getForecast?query=33.500576,-86.806931",
    "nowcast": ""
  }
}
